### ISSUE TITLE
TypeError: Cannot set property 'output' of undefined

### ISSUE THREAD

**Issue by stevenvachon** [YOU54F/cypress-multi-reporters#68]
This may be related to #43.

Here is my _cypress.json_:
```json
"reporter": "cypress-multi-reporters",
"reporterOptions": {
  "reporterEnabled": "spec, @mochajs/json-file-reporter",
  "mochajsJsonFileReporteReporterOptions": {
    "output": "/project/cypress/report.json"
  }
}
```

This error is thrown before tests start running:
```
TypeError: Cannot set property 'output' of undefined
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:344:37
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:2990:24)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9342:14)
    at Object.setPluginResolvedOn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:338:16)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:342:26
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:2990:24)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9342:14)
    at Object.setPluginResolvedOn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:338:16)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:342:26
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:2990:24)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/lodash/lodash.js:9342:14)
    at Object.setPluginResolvedOn (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:338:16)
    at Object.updateWithPluginValues (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/config.js:383:14)
    at /caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/lib/project.js:126:38
    at tryCatcher (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by YOU54F** [comment]
Hey @stevenvachon, does this work on versions prior to 0.7.x? 

Have you tried the following https://github.com/YOU54F/cypress-multi-reporters/issues/43#issuecomment-580808708

if you can provide a sample repo, I am happy to take a look.

**Comment by YOU54F** [comment]
@stevenvachon closing this due to inactivity. Please reopen with sample example repo and we can investigate if there is a reproducible issue.

Thanks!
